universe = vanilla

input = $(item)
output = $(item)_output.txt
error = $(item)_error.txt

# Job for the first script (pre.sh)
executable = pre.sh
arguments = shakespeare.tar


# Job for the second script (process.sh)
executable = process.sh
arguments = shakespeare

# Job for the third script (post.sh)
executable = post.sh
arguments = $(item)


should_transfer_files = YES
when_to_transfer_output = ON_EXIT

request_cpus = 1
request_memory = 500MB
request_disk = 100MB

queue
